name: Comment on Non-Sponsor Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Sponsor Status and Comment
        uses: actions/github-script@v7
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context)
            console.log("issue", context.issue, context.payload.issue)
            let c = context
            const issueNumber = c.issue.number
            const issueCreator = context.payload.sender.login
            const owner = c.repo.owner 
            const repo = c.repo.repo

            const r = await github.graphql(`
              query {
                user(login:"${issueCreator}") {
                  sponsorshipForViewerAsSponsorable(activeOnly:true) {
                    tier {
                      name
                      monthlyPriceInDollars
                    }  
                  }
                }
              }`
            console.log("r:", r)